[supervisord]
nodaemon=true
user=root
logfile=/app/storage/logs/supervisord.log
pidfile=/app/storage/logs/supervisord.pid

[program:php-fpm]
command=php-fpm -F
autostart=true
autorestart=true
stdout_logfile=/app/storage/logs/php-fpm.log
stderr_logfile=/app/storage/logs/php-fpm.log

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/app/storage/logs/nginx.log
stderr_logfile=/app/storage/logs/nginx.log

[program:queue-worker]
command=php /app/artisan queue:listen --tries=3 --timeout=90
autostart=true
autorestart=true
user=app
stdout_logfile=/app/storage/logs/queue-worker.log
stderr_logfile=/app/storage/logs/queue-worker.log
